### ISSUE TITLE
skia does not remove all points

### ISSUE THREAD

**Issue by typemytype** [fonttools/skia-pathops#12]
booleanOperation wise this 'iconic' E is the starting point of writing booleanOperations (checkoutlines dropped almost all contours as the area was to small to be a 'real' path)

![screen shot 2018-08-11 at 23 03 35](https://user-images.githubusercontent.com/1190358/43996058-fc3ee38a-9dba-11e8-8a08-cc3f7a023088.png)

left: the source (as pasted below)
middle: booleanOperations
right: skia

bottom right the point on the line is not removed and which should be removed

```<?xml version="1.0" encoding="UTF-8"?>
<glyph name="E" format="2">
  <advance width="693"/>
  <outline>
    <contour>
      <point x="450.0" y="217.0" type="line"/>
      <point x="442.0" y="217.0" type="line"/>
      <point x="557.0" y="515.0" type="line"/>
      <point x="565.0" y="515.0" type="line"/>
    </contour>
    <contour>
      <point x="505.0" y="370.0" type="line"/>
      <point x="502.0" y="363.0" type="line"/>
      <point x="226.0" y="363.0" type="line"/>
      <point x="229.0" y="370.0" type="line"/>
    </contour>
    <contour>
      <point x="666.0" y="478.0" type="line"/>
      <point x="658.0" y="478.0" type="line"/>
      <point x="743.0" y="700.0" type="line"/>
      <point x="751.0" y="700.0" type="line"/>
    </contour>
    <contour>
      <point x="558.0" y="0.0" type="line"/>
      <point x="550.0" y="0.0" type="line"/>
      <point x="645.0" y="246.0" type="line"/>
      <point x="653.0" y="246.0" type="line"/>
    </contour>
    <contour>
      <point x="352.0" y="695.0" type="line"/>
      <point x="361.0" y="695.0" type="line"/>
      <point x="96.0" y="5.0" type="line"/>
      <point x="88.0" y="5.0" type="line"/>
    </contour>
    <contour>
      <point x="556.0" y="7.0" type="line"/>
      <point x="553.0" y="0.0" type="line"/>
      <point x="-35.0" y="0.0" type="line"/>
      <point x="-32.0" y="7.0" type="line"/>
    </contour>
    <contour>
      <point x="745.0" y="700.0" type="line"/>
      <point x="742.0" y="693.0" type="line"/>
      <point x="230.0" y="693.0" type="line"/>
      <point x="233.0" y="700.0" type="line"/>
    </contour>
  </outline>
</glyph>
```

**Comment by anthrotype** [comment]
you mean this extra point? So you'd like to prune all the intermediate points that are exactly collinear between two parallel line segments. I guess we could do that..

![image](https://user-images.githubusercontent.com/6939968/43996713-8ab15c92-9dc0-11e8-9ced-2bd451b6896b.png)

**Comment by anthrotype** [comment]
funny enough, if you run it a second time.. it disappears :sweat_smile:

**Comment by anthrotype** [comment]
me :)

**Comment by anthrotype** [comment]
> this also a bug to me

> only it does not appear when the result is just being drawn into a bitmap

yea

**Comment by anthrotype** [comment]
the issue seems to happen only when one of these perfectly collinear points happens to be a starting point of the contour. When these occur elsewhere, they are already simplified away by Skia. I'll just strip them in the function where I reset the original starting point.

**Comment by typemytype** [comment]
oh I didnt tested with other starting point possitions...
