### ISSUE TITLE
Add INSTALL.md file (or Install section to README)

### ISSUE THREAD

**Issue by davelab6** [fonttools/skia-pathops#17]
```
$ python3 setup.py install
error: the required Cython >= 0.28.4 was not found
```

etc :)

**Comment by anthrotype** [comment]
In general, use`pip install .` to install from a local source checkout. setup.py install is deprecated (uses the old easy_install command from setuptools and creates an egg, wheres pip creates a wheel).
If it still fails upgrade pip and try again. Recent pip will bootstrap the build requirements including cython itself. 
If you can’t or don’t want to upgrade pip you can install cython separately before running  install

**Comment by anthrotype** [comment]
Also

    pip install skia-pathops

Should be enough as install instructions. You should get a precompiled wheel as released from pypi (which does not require cython or a C compiler). If you don’t get the wheel and it attempts instead to compile from source, it means you are using a python version or platform which I didn’t build wheels for (which one is that?).

For anything more than pip install skia-pathops, I would simply link to the python packaging user guide for more advanced options

**Comment by anthrotype** [comment]
I can always have the CI build more wheels of course

**Comment by davelab6** [comment]
```
$ pip3 install .
Processing /Users/dcrossland/src/github.com/fonttools/skia-pathops
  Could not find a version that satisfies the requirement mingwpy>=0.1.0b3 (from versions: )
No matching distribution found for mingwpy>=0.1.0b3
$
```

**Comment by davelab6** [comment]
`pip3 install skia-pathops` worked tho

**Comment by anthrotype** [comment]
As i said, if you upgrade pip to latest version (18) then it will work for source checkout too

**Comment by anthrotype** [comment]
Great, that's a :bug: 
I'll fix it, thanks!

**Comment by anthrotype** [comment]
oh... no it's not a bug.
You have to either

    git clone --recursive https://github.com/fonttools/skia-pathops

Or alternatively, if you have cloned normally without --recursive, you can

    git submodule update --init --recursive

Skia library is embedded as a git submodule in the fonttools/skia-pathops repository.
