### ISSUE TITLE
Activate Appveyor on the repository

### ISSUE THREAD

**Issue by anthrotype** [fonttools/skia-pathops#4]
@khaledhosny needs to enable this with his Appveyor account as this is a personal github repo (as opposed to a repo inside a github organization for which one could use an organizational Appveyor account).

**Comment by anthrotype** [comment]
the appveyor.yml is there already (e4bed05d86d378c49ca478e21035464b7874ea21)

**Comment by khaledhosny** [comment]
https://ci.appveyor.com/project/khaledhosny/skia-pathops, I don’t also mind transferring the repo to some organization.

**Comment by anthrotype** [comment]
Thanks Khaled
@behad can we host it on https://github.com/googlei18n, or even better https://github.com/fonttools?

**Comment by anthrotype** [comment]
by the way, it's building on Windows at first shot :dancer:

**Comment by behdad** [comment]
fonttools sounds good to me.

**Comment by behdad** [comment]
Skia team is interested in as well.  Let me connect you to Cary directly.

**Comment by khaledhosny** [comment]
Moved to fonttools organization for now, we can move it again if needed.

**Comment by anthrotype** [comment]
Thanks Khaled!
Do we need to reconfigure the CI hooks?
Well, we'll discover as soon as we push

**Comment by anthrotype** [comment]
ok, all CIs up and running

https://ci.appveyor.com/project/fonttools/skia-pathops
https://travis-ci.org/fonttools/skia-pathops

**Comment by anthrotype** [comment]
I don't know what's going on today with Appveyor... The Status page says it's fully operational
https://appveyor.statuspage.io/

However, ever since we moved the repository under fonttools org, it doesn't want to build. Github is sending the payload and Appveyor is receiving them but it keeps the build in queue forever.

I even tried to delete the whole thing and create anew, but no luck. :hankey:

**Comment by anthrotype** [comment]
@khaledhosny but you triggered the build manually. I don't think it will trigger automatically when we push here. I am about to push something, we'll see

**Comment by anthrotype** [comment]
all green!
