### ISSUE TITLE
Conda build failed 

### ISSUE THREAD

**Issue by gauranshkumar** [fonttools/skia-pathops#56]
Hey team, I am trying to make a conda build for this package here https://github.com/conda-forge/staged-recipes/pull/19143, but it dosen't seems to be build successfully. I have tried configuring the recipe for conda build as per the requirements but it fails at this error https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=516887&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1344 I appreciate your support in this.
Thanks!

**Comment by pavelzw** [comment]
It seems like a nightmare to fix this... The whole build process uses [custom virtual envs](https://github.com/fonttools/skia-builder/blob/0b0b4105f33633c2503164f3e57ac4ce2fdcf6cc/build_skia.py#L59) that install ninja separately from everything else and uses all different kinds of hacks that are not really compatible with conda.

**Comment by anthrotype** [comment]
I'm not familiar with conda, but if you manage to build your own standalone skia library by other means, then you can point skia-pathops to the directory where the compiled library is so it can link to it. 
You need to export environment variable `BUILD_SKIA_FROM_SOURCE=0`  before building from source to prevent setup.py from trying to build skia from source, then you export a `SKIA_LIBRARY_DIR` with the path to the directory containing the skia library (this will be passed on to setuptools' Extension.library_dirs and the linker will search in there when linking the extension module).
Someone also contributed support for finding skia using pkg-config (see https://github.com/fonttools/skia-pathops/pull/54), not sure if that's of interest for conda.
I hope that helps..

**Comment by pavelzw** [comment]
@naveen521kk added skin-pathops to conda-forge in [conda-forge/staged-recipes #19570](https://github.com/conda-forge/staged-recipes/pull/19570) :rocket:. So this issue can be closed.
