### ISSUE TITLE
if one of the starting points is still in the result

### ISSUE THREAD

**Issue by typemytype** [fonttools/skia-pathops#9]
it should be the starting point of the merged path

**Comment by adrientetar** [comment]
note on this: there might be multiple "original starting points" for the same contour (if two contours merged) in which case we should normalize by minimizing squared distance to origin.

**Comment by typemytype** [comment]
fe see https://github.com/typemytype/booleanOperations/blob/master/Lib/booleanOperations/flatten.py#L688

I forgot about the logic, when there are multiple found staring points: I guess booleanOperations sets the first found as the starting point of the new merged contour.

**Comment by anthrotype** [comment]
I think I fixed this as well (https://github.com/fonttools/skia-pathops/commit/4e199f69fcee450f647d93cdf71f4c2f9fdebbc9), please test

**Comment by typemytype** [comment]
much better, idd

(finding some errors, will try to post them in operate threads)
